// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// compute_augmentation_cpp
arma::vec compute_augmentation_cpp(const arma::mat& va, const arma::mat& vb, const arma::mat& fisher, const arma::mat& k_rs, const arma::mat& k_stu, const arma::mat& k_s_tu);
RcppExport SEXP _brm_compute_augmentation_cpp(SEXP vaSEXP, SEXP vbSEXP, SEXP fisherSEXP, SEXP k_rsSEXP, SEXP k_stuSEXP, SEXP k_s_tuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type va(vaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type vb(vbSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type fisher(fisherSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type k_rs(k_rsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type k_stu(k_stuSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type k_s_tu(k_s_tuSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_augmentation_cpp(va, vb, fisher, k_rs, k_stu, k_s_tu));
    return rcpp_result_gen;
END_RCPP
}
// mat_vec_mul
arma::mat mat_vec_mul(const arma::mat& m, const arma::colvec& v);
RcppExport SEXP _brm_mat_vec_mul(SEXP mSEXP, SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type m(mSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(mat_vec_mul(m, v));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_brm_compute_augmentation_cpp", (DL_FUNC) &_brm_compute_augmentation_cpp, 6},
    {"_brm_mat_vec_mul", (DL_FUNC) &_brm_mat_vec_mul, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_brm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
