# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_augmentation_cpp <- function(va, vb, fisher, k_rs, k_stu, k_s_tu) {
  .Call(`_brmplus_compute_augmentation_cpp`, va, vb, fisher, k_rs, k_stu, k_s_tu)
}

mat_vec_mul <- function(m, v) {
  .Call(`_brmplus_mat_vec_mul`, m, v)
}
